# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    VIDEO_QUALITY_ITEMS = (
        "144p",
        "240p",
        "360p",
        "480p",
        "720p (HD)",
        "1080p (Full HD)",
        "1440p (2K)",
        "2160p (4K)",
        "Best available",
    )
    VIDEO_FORMAT_ITEMS = ("Any", "mp4", "webm", "avi", "mov", "mkv", "flv", "3gp")
    AUDIO_QUALITY_ITEMS = (
        "32 kbps",
        "64 kbps",
        "128 kbps",
        "160 kbps",
        "192 kbps",
        "256 kbps",
        "320 kbps",
        "Best available",
    )
    AUDIO_FORMAT_ITEMS = (
        "Any",
        "mp3",
        "ogg / oga [Vorbis]",
        "m4a",
        "aac",
        "opus",
        "flac",
        "wav",
    )
    PROXY_TYPE_ITEMS = ("None", "HTTPS", "SOCKS4", "SOCKS5")

    def setupUi(self, Settings):
        self._configure_root(Settings)
        self._create_buttons(Settings)
        self._create_video_format_section(Settings)
        self._create_audio_format_section(Settings)
        self._create_proxy_section(Settings)
        self._create_download_dir_section(Settings)
        self._create_misc_section(Settings)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def _configure_root(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(954, 582)
        Settings.setFont(self._arial_font())

    def _create_buttons(self, Settings):
        self.save_button = QtWidgets.QPushButton(parent=Settings)
        self.save_button.setGeometry(QtCore.QRect(330, 510, 80, 31))
        self.save_button.setObjectName("save_button")
        self.close_button = QtWidgets.QPushButton(parent=Settings)
        self.close_button.setGeometry(QtCore.QRect(500, 510, 80, 31))
        self.close_button.setObjectName("close_button")

    def _create_video_format_section(self, Settings):
        self.layoutWidget = QtWidgets.QWidget(parent=Settings)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 180, 451, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vid_quality_hlayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.vid_quality_hlayout.setContentsMargins(0, 0, 0, 0)
        self.vid_quality_hlayout.setObjectName("vid_quality_hlayout")
        self.pref_vid_quality_label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.pref_vid_quality_label.setObjectName("pref_vid_quality_label")
        self.vid_quality_hlayout.addWidget(self.pref_vid_quality_label)
        self.pref_vid_quality_dropdown = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.pref_vid_quality_dropdown.setFont(self._mono_font())
        self.pref_vid_quality_dropdown.setObjectName("pref_vid_quality_dropdown")
        self.pref_vid_quality_dropdown.addItems([""] * 9)
        self.vid_quality_hlayout.addWidget(self.pref_vid_quality_dropdown)

        self.layoutWidget_2 = QtWidgets.QWidget(parent=Settings)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 110, 451, 51))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.pref_video_format_layout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.pref_video_format_layout.setContentsMargins(0, 0, 0, 0)
        self.pref_video_format_layout.setObjectName("pref_video_format_layout")
        self.pref_vid_format = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.pref_vid_format.setObjectName("pref_vid_format")
        self.pref_video_format_layout.addWidget(self.pref_vid_format)
        self.pref_vid_format_dropdown = QtWidgets.QComboBox(parent=self.layoutWidget_2)
        self.pref_vid_format_dropdown.setFont(self._mono_font())
        self.pref_vid_format_dropdown.setObjectName("pref_vid_format_dropdown")
        self.pref_vid_format_dropdown.addItems([""] * 8)
        self.pref_video_format_layout.addWidget(self.pref_vid_format_dropdown)

    def _create_audio_format_section(self, Settings):
        self.layoutWidget_3 = QtWidgets.QWidget(parent=Settings)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 320, 451, 51))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.audio_quality_hlayout = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.audio_quality_hlayout.setContentsMargins(0, 0, 0, 0)
        self.audio_quality_hlayout.setObjectName("audio_quality_hlayout")
        self.audio_quality_label = QtWidgets.QLabel(parent=self.layoutWidget_3)
        self.audio_quality_label.setObjectName("audio_quality_label")
        self.audio_quality_hlayout.addWidget(self.audio_quality_label)
        self.pref_aud_quality_dropdown = QtWidgets.QComboBox(parent=self.layoutWidget_3)
        self.pref_aud_quality_dropdown.setFont(self._mono_font())
        self.pref_aud_quality_dropdown.setObjectName("pref_aud_quality_dropdown")
        self.pref_aud_quality_dropdown.addItems([""] * 8)
        self.audio_quality_hlayout.addWidget(self.pref_aud_quality_dropdown)

        self.layoutWidget_4 = QtWidgets.QWidget(parent=Settings)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 250, 458, 51))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.pref_audio_format_layout = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.pref_audio_format_layout.setContentsMargins(0, 0, 0, 0)
        self.pref_audio_format_layout.setObjectName("pref_audio_format_layout")
        self.pref_aud_format = QtWidgets.QLabel(parent=self.layoutWidget_4)
        self.pref_aud_format.setObjectName("pref_aud_format")
        self.pref_audio_format_layout.addWidget(self.pref_aud_format)
        self.pref_aud_format_dropdown = QtWidgets.QComboBox(parent=self.layoutWidget_4)
        self.pref_aud_format_dropdown.setFont(self._mono_font())
        self.pref_aud_format_dropdown.setObjectName("pref_aud_format_dropdown")
        self.pref_aud_format_dropdown.addItems([""] * 8)
        self.pref_audio_format_layout.addWidget(self.pref_aud_format_dropdown)

    def _create_proxy_section(self, Settings):
        self.layoutWidget_5 = QtWidgets.QWidget(parent=Settings)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 390, 711, 72))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.proxy_server_layout = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.proxy_server_layout.setContentsMargins(0, 0, 0, 0)
        self.proxy_server_layout.setObjectName("proxy_server_layout")
        self.proxy_label = QtWidgets.QLabel(parent=self.layoutWidget_5)
        self.proxy_label.setObjectName("proxy_label")
        self.proxy_server_layout.addWidget(self.proxy_label)
        self.proxy_server_type = QtWidgets.QComboBox(parent=self.layoutWidget_5)
        self.proxy_server_type.setFont(self._mono_font())
        self.proxy_server_type.setObjectName("proxy_server_type")
        self.proxy_server_type.addItems([""] * 4)
        self.proxy_server_layout.addWidget(self.proxy_server_type)
        self.proxy_server_label = QtWidgets.QLabel(parent=self.layoutWidget_5)
        self.proxy_server_label.setObjectName("proxy_server_label")
        self.proxy_server_layout.addWidget(self.proxy_server_label)
        self.proxy_server_addr = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        self.proxy_server_addr.setFont(self._mono_font())
        self.proxy_server_addr.setObjectName("proxy_server_addr")
        self.proxy_server_layout.addWidget(self.proxy_server_addr)
        self.proxy_port_label = QtWidgets.QLabel(parent=self.layoutWidget_5)
        self.proxy_port_label.setObjectName("proxy_port_label")
        self.proxy_server_layout.addWidget(self.proxy_port_label)
        self.proxy_server_port = QtWidgets.QLineEdit(parent=self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proxy_server_port.sizePolicy().hasHeightForWidth())
        self.proxy_server_port.setSizePolicy(sizePolicy)
        self.proxy_server_port.setMaximumSize(QtCore.QSize(70, 16777215))
        self.proxy_server_port.setFont(self._mono_font())
        self.proxy_server_port.setObjectName("proxy_server_port")
        self.proxy_server_layout.addWidget(self.proxy_server_port)

    def _create_download_dir_section(self, Settings):
        self.layoutWidget_6 = QtWidgets.QWidget(parent=Settings)
        self.layoutWidget_6.setGeometry(QtCore.QRect(20, 40, 601, 72))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.dl_dir_layout = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.dl_dir_layout.setContentsMargins(0, 0, 0, 0)
        self.dl_dir_layout.setObjectName("dl_dir_layout")
        self.save_downloads_label = QtWidgets.QLabel(parent=self.layoutWidget_6)
        self.save_downloads_label.setObjectName("save_downloads_label")
        self.dl_dir_layout.addWidget(self.save_downloads_label)
        self.save_downloads_edit = QtWidgets.QLineEdit(parent=self.layoutWidget_6)
        self.save_downloads_edit.setObjectName("save_downloads_edit")
        self.dl_dir_layout.addWidget(self.save_downloads_edit)
        self.browse_btn = QtWidgets.QPushButton(parent=self.layoutWidget_6)
        self.browse_btn.setFont(self._mono_font(bold=True))
        self.browse_btn.setObjectName("browse_btn")
        self.dl_dir_layout.addWidget(self.browse_btn)

    def _create_misc_section(self, Settings):
        self.layoutWidget_7 = QtWidgets.QWidget(parent=Settings)
        self.layoutWidget_7.setGeometry(QtCore.QRect(520, 120, 414, 125))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.check_download_thumbnails = QtWidgets.QCheckBox(parent=self.layoutWidget_7)
        self.check_download_thumbnails.setObjectName("check_download_thumbnails")
        self.verticalLayout.addWidget(self.check_download_thumbnails)
        self.check_audio_only = QtWidgets.QCheckBox(parent=self.layoutWidget_7)
        self.check_audio_only.setObjectName("check_audio_only")
        self.verticalLayout.addWidget(self.check_audio_only)
        self.label = QtWidgets.QLabel(parent=self.layoutWidget_7)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget_7)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget_7)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)

    @staticmethod
    def _mono_font(bold=False):
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(bold)
        return font

    @staticmethod
    def _arial_font():
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        return font

    @staticmethod
    def _set_combo_items(combo_box, context, values):
        _translate = QtCore.QCoreApplication.translate
        for index, text in enumerate(values):
            combo_box.setItemText(index, _translate(context, text))

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.save_button.setText(_translate("Settings", "Save"))
        self.close_button.setText(_translate("Settings", "Close"))
        self.pref_vid_quality_label.setText(_translate("Settings", "Preferred video quality:"))
        self._set_combo_items(self.pref_vid_quality_dropdown, "Settings", self.VIDEO_QUALITY_ITEMS)
        self.pref_vid_format.setText(_translate("Settings", "Preferred video format:"))
        self._set_combo_items(self.pref_vid_format_dropdown, "Settings", self.VIDEO_FORMAT_ITEMS)
        self.audio_quality_label.setText(_translate("Settings", "Preferred audio quality:"))
        self._set_combo_items(self.pref_aud_quality_dropdown, "Settings", self.AUDIO_QUALITY_ITEMS)
        self.pref_aud_format.setText(_translate("Settings", "Preferred audio format:"))
        self._set_combo_items(self.pref_aud_format_dropdown, "Settings", self.AUDIO_FORMAT_ITEMS)
        self.proxy_label.setText(_translate("Settings", "SOCKS / proxy:"))
        self._set_combo_items(self.proxy_server_type, "Settings", self.PROXY_TYPE_ITEMS)
        self.proxy_server_label.setText(_translate("Settings", "Server:"))
        self.proxy_port_label.setText(_translate("Settings", "Port:"))
        self.save_downloads_label.setText(_translate("Settings", "Save downloads to:"))
        self.browse_btn.setText(_translate("Settings", "Browse"))
        self.check_download_thumbnails.setText(_translate("Settings", "Download thumbnails"))
        self.check_audio_only.setText(_translate("Settings", "Only the associated audio tracks"))
        self.label.setText(_translate("Settings", "(Entire videos may be downloaded, then"))
        self.label_2.setText(_translate("Settings", "audio would be extracted and the videos"))
        self.label_3.setText(_translate("Settings", "will be deleted.)"))
