# Form implementation generated from reading ui file 'login_prompt.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginPromptDialog(object):
    def setupUi(self, LoginPromptDialog):
        LoginPromptDialog.setObjectName("LoginPromptDialog")
        LoginPromptDialog.resize(435, 270)
        font = QtGui.QFont()
        font.setFamily("Arial")
        LoginPromptDialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginPromptDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=LoginPromptDialog)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.checkBox = QtWidgets.QCheckBox(parent=LoginPromptDialog)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=LoginPromptDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(LoginPromptDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginPromptDialog)

    def retranslateUi(self, LoginPromptDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginPromptDialog.setWindowTitle(_translate("LoginPromptDialog", "Login Prompt"))
        self.label.setText(_translate("LoginPromptDialog", "This login process will allow you to download private, age-restricted or premium content using your YouTube account. When you log in, this app will download media on behalf of your account. You can log out with a single click from the same menu."))
        self.checkBox.setText(_translate("LoginPromptDialog", "Do not show this message again"))
